### ISSUE TITLE
Broken readme link (504 Gateway Time-out)

### ISSUE THREAD

**Issue by owenchu** [yjlou/2019-nCov#12]
The readme link (https://ppt.cc/fgrRBx) is broken. I'm not sure where the link  is supposed to point. Anyone?

**Comment by Stimim** [comment]
It should be https://docs.google.com/document/d/e/2PACX-1vT2cvKSkICCRl6VpXpEsnJcZRSiS2p6VVYlNaR6KRkXAyE4HkdGxKb_sdf2H2WejyUjuRvsJhSaOppx/pub

I'm not sure what's going on at ppt.cc site, the Google doc link still works.
I will fix it later.

**Comment by Stimim** [comment]
6071000d56d24ba8311aa4c2fd4956a0f12fa169 should fix the issue.
