### ISSUE TITLE
Broken repo link

### ISSUE THREAD

**Issue by mingjunlu** [yjlou/2019-nCov#17]
I just found that the link of this repo (https://pandemic.events) is broken. According to [this commit](https://github.com/yjlou/2019-nCov/commit/068ab43cb1bea440c5d1614b0ac174d46d8b78b1), maybe it should also be changed from `https://pandemic.events` to `https://yjlou.github.io/2019-nCov/`?
![截圖 2021-05-15 下午2 09 22](https://user-images.githubusercontent.com/40516784/118350061-45ba9400-b587-11eb-8768-dcaf849f5224.png)

**Comment by yjlou** [comment]
Thanks for the report. Fixed in https://github.com/yjlou/2019-nCov/commit/df0640ac58c3884dd0a4d85ee9d89269382ba7a9
