### ISSUE TITLE
Historical location data download issue

### ISSUE THREAD

**Issue by junwei0117** [yjlou/2019-nCov#5]
### Description 
When you choose the history range in step 2, it will not actually download the historical data of that period, but only the data of that day.

### Expected behavior 
I chose the last three days as the period, I should get below files:
- history-2020-02-28.kml
- history-2020-02-29.kml
- history-2020-03-01.kml

### Actual behavior 
I chose the last three days as the period, but I only get one files:
- history-2020-02-28.kml

**Comment by junwei0117** [comment]
I found the problem, the browser rejected multiple popups.

Thanks your project :)

**Comment by Stimim** [comment]
Good to know that you've solved the issue.
Do you think the instruction on the website is clear enough?
Do you have any feedback that you think we can improve?
